#!/usr/bin/env bash
# build-skill-map.sh — regenerate ~/.claude/hooks/skill-map from SKILL.md files.
#
# Uses the `claude` CLI to infer file-path glob patterns for each skill under
# ~/.claude/skills/. Run this when you add or significantly change a skill.
# Output is a tab-separated <glob>\t<skill-name> map consumed by remind-skill.sh.
# The output is hand-editable — re-running overwrites it.
#
# Usage:
#   build-skill-map.sh                # regenerate from all skills
#   build-skill-map.sh moov-migration # regenerate entries for a single skill
#                                     # (preserves other entries in the map)

set -euo pipefail

SKILLS_DIR="${SKILLS_DIR:-${HOME}/.claude/skills}"
MAP="${SKILL_MAP:-${HOME}/.claude/hooks/skill-map}"
ONLY="${1:-}"

if ! command -v claude >/dev/null 2>&1; then
  echo "claude CLI not found in PATH" >&2
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

PROMPT_HEADER='You are inferring file-path glob patterns that should trigger consulting a Claude Code skill before editing a matching file. Read the SKILL.md below and output up to 5 strong-signal globs, ONE PER LINE, nothing else. Globs use shell wildcards (*, **, ?) and should match the kind of paths Claude would see when editing files (e.g. "*/migrations/*.sql", "*_test.go", "**/handlers/*.go"). Prefer specificity over breadth. Do NOT include explanations, headers, code fences, or commentary. If no path patterns are a strong signal for this skill, output exactly: NONE'

infer_for_skill() {
  local skill_md="$1"
  local name="$2"
  local prompt
  prompt=$(printf '%s\n\nSkill name: %s\n\n--- SKILL.md ---\n%s' \
    "$PROMPT_HEADER" "$name" "$(cat "$skill_md")")
  printf '%s' "$prompt" | claude -p 2>/dev/null || true
}

process_skill() {
  local skill_md="$1"
  local name
  name=$(basename "$(dirname "$skill_md")")
  echo "→ $name" >&2

  local output
  output=$(infer_for_skill "$skill_md" "$name")
  if [ -z "$output" ]; then
    echo "  (no output)" >&2
    return
  fi
  if echo "$output" | grep -qxiF "NONE"; then
    echo "  (no triggers)" >&2
    return
  fi

  while IFS= read -r line; do
    local glob
    glob=$(echo "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
    [ -z "$glob" ] && continue
    case "$glob" in
      '#'*|NONE|none) continue ;;
      '`'*) glob=$(echo "$glob" | tr -d '`') ;;
    esac
    # Drop obvious non-globs (sentences, markdown bullets)
    case "$glob" in
      '- '*) glob="${glob#- }" ;;
      '* '*) glob="${glob#\* }" ;;
    esac
    [ -z "$glob" ] && continue
    printf '%s\t%s\n' "$glob" "$name" >> "$TMP"
    echo "  $glob" >&2
  done <<< "$output"
}

if [ -n "$ONLY" ]; then
  skill_md="$SKILLS_DIR/$ONLY/SKILL.md"
  if [ ! -f "$skill_md" ]; then
    echo "No SKILL.md at $skill_md" >&2
    exit 1
  fi
  # Preserve existing entries for other skills.
  if [ -f "$MAP" ]; then
    grep -v -P "\t${ONLY}$" "$MAP" > "$TMP" || true
  fi
  process_skill "$skill_md"
else
  for skill_md in "$SKILLS_DIR"/*/SKILL.md; do
    [ -f "$skill_md" ] || continue
    process_skill "$skill_md"
  done
fi

mkdir -p "$(dirname "$MAP")"
{
  echo "# Generated by build-skill-map.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Format: <glob>\\t<skill-name>  (# starts a comment, blank lines ignored)"
  echo "# Re-running this script overwrites the file; hand-edits are lost."
  echo "# To refresh a single skill: build-skill-map.sh <skill-name>"
  echo ""
  # Strip any prior header lines and sort uniquely.
  grep -v '^#' "$TMP" | grep -v '^$' | sort -u
} > "${MAP}.new"
mv "${MAP}.new" "$MAP"

n=$(grep -cv '^#\|^$' "$MAP" || true)
echo "Wrote $n entries to $MAP" >&2
